<?php
$menu = array(
	array(
		'name'=>$this->_lang['langHeadMyIsBuy'],
		'id'=>'buyer',
		'url'=>'own_main.php',
		'body'=>array(
			array(
				'name'=>$this->_lang['langHeadMyIsBuy'],
				'id'=>'my_buyer',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadAlreadyBuyBaby'],
						'id'=>'ready_buy',
						'url'=>'own_order.php?action=bought',
					),
					array(
						'name'=>$this->_lang['langHeadAuctionBaby'],
						'id'=>'auctioning_buy',
						'url'=>'own_product_list.php?action=auction',
					),
					array(
						'name'=>$this->_lang['langHeadCountdownBaby'],
						'id'=>'countdown_buy_bid',
						'url'=>'own_countdown_bid.php?action=list',
					),					
					array(
						'name'=>$this->_lang['langHeadMyCollection'],
						'id'=>'my_collection',
						'url'=>'own_collection.php?genre=product',
					),
					array(
						'name'=>$this->_lang['langHeadSaleRevertMessage'],
						'id'=>'sale_revert',
						'url'=>'own_productmessage.php?action=buy',
					),
				),
			),
		),
	),
	array(
		'name'=>$this->_lang['langHeadMyIsSale'],
		'id'=>'seller',
		'url'=>'own_order.php?action=sold',
		'body'=>array(
			array(
				'name'=>$this->_lang['langHeadMyIsSale'],
				'id'=>'my_seller',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadSale'],
						'id'=>'to_sale',
						'url'=>'own_product.php?action=sell',
					),
					array(
						'name'=>$this->_lang['langHeadAlreadySaleBaby'],
						'id'=>'ready_sale',
						'url'=>'own_order.php?action=sold',
					),
					array(
						'name'=>$this->_lang['langHeadVendBaby'],
						'id'=>'selling',
						'url'=>'own_product_list.php?action=list',
					),
					array(
						'name'=>$this->_lang['langHeadStorageBaby'],
						'id'=>'storage',
						'url'=>'own_product_list.php?action=list_instock',
					),
					array(
						'name'=>$this->_lang['langHeadBuyMessageRevert'],
						'id'=>'buy_revert',
						'url'=>'own_productmessage.php?action=sale',
					),
					array(
						'name'=>$this->_lang['langHeadProductBatch'],
						'id'=>'product_batch',
						'url'=>'own_product_batch.php',
					),
					array(
						'name'=>$this->_lang['langHeadPersonalCertify'],
						'id'=>'personal_certify',
						'url'=>'own_member.php?action=personal_certify',
					),
					array(
						'name'=>$this->_lang['langHeadRealityShopAttestation'],
						'id'=>'entity_check',
						'url'=>'own_shop.php?action=entity_check',
					),
					array(
						'name'=>$this->_lang['langHeadBindPayment'],
						'id'=>'bind_payment',
						'url'=>'own_payment.php',
					),
				),
			),
			array(
				'name'=>$this->_lang['langHeadMemberStatics'],
				'id'=>'seller_statics',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadMemberStaticsMember'],
						'id'=>'seller_statics_member',
						'url'=>'own_statics.php?action=member',
					),
					array(
						'name'=>$this->_lang['langHeadMemberStaticsOrder'],
						'id'=>'seller_statics_order',
						'url'=>'own_statics.php?action=order',
					),
					array(
						'name'=>$this->_lang['langHeadMemberStaticsProduct'],
						'id'=>'seller_statics_product',
						'url'=>'own_statics.php?action=product',
					),
				),
			),
			array(
				'name'=>$this->_lang['langHeadMemberPostage'],
				'id'=>'postage',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadMemberPostageTplAdd'],
						'id'=>'postage_tpl_add',
						'url'=>'own_postage.php?action=add',
					),
					array(
						'name'=>$this->_lang['langHeadMemberPostageTpl'],
						'id'=>'postage_tpl',
						'url'=>'own_postage.php?action=list',
					),
				),
			),
		),
	),
	array(
		'name'=>$this->_lang['langHeadMemberAccount'],
		'id'=>'account',
		'url'=>'own_member.php',
		'body'=>array(
			array(
				'name'=>$this->_lang['langHeadAppraiseManage'],
				'id'=>'appraise_manage',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadAppraiseManage'],
						'id'=>'appraise_list',
						'url'=>'own_score.php',
					),
				),
			),
			array(
				'name'=>$this->_lang['langHeadClientServer'],
				'id'=>'client_server',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadComplaintLaw'],
						'id'=>'complaint_law',
						'url'=>'own_complaint.php',
					),
					array(
						'name'=>$this->_lang['langHeadCreditsLogList'],
						'id'=>'credits_log',
						'url'=>'own_credits.php',
					),
				),
			),
			array(
				'name'=>$this->_lang['langHeadBasicSet'],
				'id'=>'basic_set',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadInfoPassword'],
						'id'=>'info_password',
						'url'=>'own_member.php',
					),
					array(
						'name'=>$this->_lang['langHeadWebRemindSet'],
						'id'=>'remind_set',
						'url'=>'own_remind.php',
					),
					array(
						'name'=>$this->_lang['langHeadConsigneeAddress'],
						'id'=>'consignee_address',
						'url'=>'own_receive.php',
					),
				),
			),
			array(
				'name'=>$this->_lang['langHeadPredeposit'],
				'id'=>'predeposit',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadPrePay'],
						'id'=>'to_pre_pay',
						'url'=>'own_predeposit.php?action=pay',
					),
					array(
						'name'=>$this->_lang['langHeadPreCash'],
						'id'=>'to_pre_cash',
						'url'=>'own_predeposit.php?action=cash_set',
					),
					array(
						'name'=>$this->_lang['langHeadPreDetailView'],
						'id'=>'pre_detail_view',
						'url'=>'own_predeposit.php?action=list',
					),
					array(
						'name'=>$this->_lang['langHeadPreRecordView'],
						'id'=>'pre_record_view',
						'url'=>'own_predeposit.php?action=record_list',
					),
					array(
						'name'=>$this->_lang['langHeadPreCashView'],
						'id'=>'pre_cash_view',
						'url'=>'own_predeposit.php?action=cash_list',
					),
				),
			),
			array(
				'name'=>$this->_lang['langHeadMemberSiteMessage'],
				'id'=>'site_message',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadMemberSiteMessageManage'],
						'id'=>'site_message_manage',
						'url'=>'own_message.php',
					),
					array(
						'name'=>$this->_lang['langHeadMemberSiteMessageSend'],
						'id'=>'site_message_send',
						'url'=>'own_message.php?action=add',
					)
				)
			)
		),
	),
	array(
		'name'=>$this->_lang['langCMyShop'],
		'id'=>'my_shop',
		'url'=>'own_shop.php?action=modi',
		'body'=>array(
			array(
				'name'=>$this->_lang['langHeadManageShop'],
				'id'=>'shop_manage',
				'url'=>'',
				'body'=>array(
					array(
						'name'=>$this->_lang['langHeadLookShop'],
						'id'=>'view_shop',
						'url'=>'own_shop.php?action=view',
						'target'=>'1',
					),
					array(
						'name'=>$this->_lang['langHeadFreeOpenShop'],
						'id'=>'add_shop',
						'url'=>'own_shop.php?action=new',
					),
					array(
						'name'=>$this->_lang['langHeadManageShop'],
						'id'=>'manage_shop',
						'url'=>'own_shop.php?action=modi',
					),
					array(
						'name'=>$this->_lang['langHeadBabyClass'],
						'id'=>'baby_class',
						'url'=>'own_shopproductcate.php',
					),
					array(
						'name'=>$this->_lang['langHeadShopPlace'],
						'id'=>'shop_map',
						'url'=>'own_shopmap.php',
					),
					array(
						'name'=>$this->_lang['langHeadCommendBaby'],
						'id'=>'commend_baby',
						'url'=>'own_shopproduct.php?action=recommended_list',
					),
					array(
						'name'=>$this->_lang['langHeadFirendLink'],
						'id'=>'firend_link',
						'url'=>'own_shoplink.php',
					),
					array(
						'name'=>$this->_lang['langHeadShopMessage'],
						'id'=>'shop_message',
						'url'=>'own_shopmessage.php',
					),
					array(
						'name'=>$this->_lang['langHeadShopStyle'],
						'id'=>'shop_style',
						'url'=>'own_shopstyle.php',
					),
					array(
						'name'=>$this->_lang['langHeadShopIntro'],
						'id'=>'shop_intro',
						'url'=>'own_shop.php?action=intro',
					),
					array(
						'name'=>$this->_lang['langHeadShopTag'],
						'id'=>'shop_tag',
						'url'=>'own_shoptag.php',
					),
				),
			),
		),
	),
);
?>